name: Run MATLAB Tests on GitHub-Hosted Runner
on: [push]
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest] #, macos-latest, windows-latest]
        release: [R2020a,R2021a, R2022a]
    name: Run MATLAB Tests and Generate Artifacts
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with: 
            release: ${{matrix.release}}
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with: 
            select-by-folder: test
            select-by-tag: Github
            

